In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("../data/movies.csv")
ratings = pd.read_csv("../data/ratings.csv")

In [3]:
movies.sample(5)

,movieId,title,genres
5932,34072,"March of the Penguins (Marche de l'empereur, L...",Documentary
833,1094,"Crying Game, The (1992)",Drama|Romance|Thriller
688,906,Gaslight (1944),Drama|Thriller
2379,3157,Stuart Little (1999),Children|Comedy|Fantasy
6667,57502,Cat Soup (Nekojiru-so) (2001),Adventure|Animation|Drama|Horror

In [4]:
ratings.sample(5)

       userId  movieId  rating   timestamp
79701     495    80906     4.5  1458636775
11321      68    50685     4.5  1305150762
3655       21   164179     4.0  1500701551
43209     290      296     5.0   975031374
50605     326    96829     4.0  1419880819

In [5]:
movies.shape

(9742, 3)

In [6]:
ratings.shape

(100836, 4)

In [7]:
movies.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [8]:
ratings.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [10]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [11]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [12]:
ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [13]:
movies.duplicated().sum()

np.int64(0)

In [14]:
ratings.duplicated().sum()

np.int64(0)

In [15]:
ratings["userId"].nunique()

610

In [16]:
movies["movieId"].nunique()

9742

In [17]:
ratings['rating'].value_counts().sort_index()

rating
0.5     1370
1.0     2811
1.5     1791
2.0     7551
2.5     5550
3.0    20047
3.5    13136
4.0    26818
4.5     8551
5.0    13211
Name: count, dtype: int64

In [18]:
most_rated_movies=(
    ratings["movieId"].value_counts().reset_index()
)
most_rated_movies.columns=["movieId","rating_count"]
most_rated_movies=most_rated_movies.merge(movies,on="movieId")
most_rated_movies.sample(5)

,movieId,rating_count,title,genres
8667,7891,1,"Last Man on Earth, The (Ultimo uomo della Terr...",Drama|Horror|Sci-Fi
8374,7083,1,Sweet Dreams (1985),Drama
1551,1894,16,Six Days Seven Nights (1998),Adventure|Comedy|Romance
6713,72591,1,"Patriot, The (1998)",Action|Thriller
3838,3846,4,Easy Money (1983),Comedy