In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("../data/movies.csv")
ratings = pd.read_csv("../data/ratings.csv")

In [3]:
movies.sample(5)

      movieId                         title                genres
5488    26322     Gone in 60 Seconds (1974)    Action|Crime|Drama
3782     5288       Atomic Cafe, The (1982)       Documentary|War
8221   103801       Drinking Buddies (2013)  Comedy|Drama|Romance
157       186            Nine Months (1995)        Comedy|Romance
3815     5345  Triumph of the Spirit (1989)                 Drama

In [4]:
ratings.sample(5)

       userId  movieId  rating   timestamp
86612     561      380     3.5  1491091137
69721     448    49649     1.0  1192302220
53577     353      588     3.0   831939590
62906     414     1769     3.0   961516093
20945     139     5881     0.5  1453925119

In [5]:
movies.shape

(9742, 3)

In [6]:
ratings.shape

(100836, 4)

In [7]:
movies.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [8]:
ratings.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [9]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

In [10]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [11]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [12]:
ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [13]:
movies.duplicated().sum()

np.int64(0)

In [14]:
ratings.duplicated().sum()

np.int64(0)

In [15]:
ratings["userId"].nunique()

610

In [16]:
movies["movieId"].nunique()

9742

In [17]:
ratings['rating'].value_counts().sort_index()

rating
0.5     1370
1.0     2811
1.5     1791
2.0     7551
2.5     5550
3.0    20047
3.5    13136
4.0    26818
4.5     8551
5.0    13211
Name: count, dtype: int64

In [18]:
most_rated_movies=(
    ratings["movieId"].value_counts().reset_index()
)
most_rated_movies.columns=["movieId","rating_count"]
most_rated_movies=most_rated_movies.merge(movies,on="movieId")
most_rated_movies.sample(5)

,movieId,rating_count,title,genres
1310,1693,19,Amistad (1997),Drama|Mystery
3502,62250,5,Gomorrah (Gomorra) (2008),Crime|Drama
3463,881,5,First Kid (1996),Children|Comedy
7419,86068,1,Films to Keep You Awake: The Christmas Tale (P...,Horror|Thriller
829,88140,32,Captain America: The First Avenger (2011),Action|Adventure|Sci-Fi|Thriller|War

In [ ]:
avg_rating=(
    ratings.groupby("movieId")["rating"].mean()
    .reset_index(name="avg_rating")
)
most_rated_movies = most_rated_movies.merge(
    avg_rating,on="movieId"
)
most_rated_movies.sample(5)

,movieId,rating_count,title,genres,avg_rating
8014,133798,1,Hot Pursuit (2015),Action|Comedy,1.500000
1798,73,13,"Misérables, Les (1995)",Drama|War,3.461538
2124,5380,10,"Importance of Being Earnest, The (2002)",Comedy|Drama|Romance,3.850000
9673,89072,1,Stake Land (2010),Horror,4.000000
4307,1609,3,187 (One Eight Seven) (1997),Drama|Thriller,2.666667

In [20]:
movies["genres"].head(10)

0    Adventure|Animation|Children|Comedy|Fantasy
1                     Adventure|Children|Fantasy
2                                 Comedy|Romance
3                           Comedy|Drama|Romance
4                                         Comedy
5                          Action|Crime|Thriller
6                                 Comedy|Romance
7                             Adventure|Children
8                                         Action
9                      Action|Adventure|Thriller
Name: genres, dtype: object

In [21]:
all_genres=movies["genres"].str.split("|").explode().unique()
all_genres

array(['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Mystery', 'Sci-Fi', 'War', 'Musical', 'Documentary', 'IMAX',
       'Western', 'Film-Noir', '(no genres listed)'], dtype=object)

In [23]:
n=int(input("Enter number of members: "))
members_genres=[]
for i in range(n):
    genres=input(f"Enter genres for member {i+1},seprated by commas: "
    ).split(",")
    genres=[genre.strip() for genre in genres]
    members_genres.append(genres)
print(members_genres)

[['comedy', 'romantic', 'fantasy', 'adventure', 'comedy'], ['fantasy'], ['children'], ['romantic'], ['drama']]

In [24]:
group_genres=[]
for genres in members_genres:
    group_genres.extend(genres)
print(group_genres)

['comedy', 'romantic', 'fantasy', 'adventure', 'comedy', 'fantasy', 'children', 'romantic', 'drama']

In [25]:
from collections import Counter
genres_counts=Counter(group_genres)
print(genres_counts)

Counter({'comedy': 2, 'romantic': 2, 'fantasy': 2, 'adventure': 1, 'children': 1, 'drama': 1})

In [26]:
movies["genres"]=movies["genres"].str.split("|")
most_rated_movies["genres"]=(most_rated_movies['genres'].str.split("|"))

In [27]:
from collections import Counter
genre_counts = Counter()
for genres in members_genres:
    genre_counts.update(set(genres))
print(genre_counts)

Counter({'romantic': 2, 'fantasy': 2, 'adventure': 1, 'comedy': 1, 'children': 1, 'drama': 1})